"""
Simple Python to 4GL reverse converter.

This is a basic implementation that works primarily for Python code
generated by the 4GL to Python converter.
"""

import ast
from typing import List


class PythonTo4GLConverter:
    """Convert Python code back to 4GL."""

    def __init__(self):
        self.indent_level = 0
        self.output: List[str] = []
        self.variables: dict[str, str] = {}  # var_name -> type

    def convert(self, python_code: str) -> str:
        """Convert Python code to 4GL."""
        try:
            tree = ast.parse(python_code)
            self.output = []
            self.variables = {}
            self.indent_level = 0

            # Process the AST
            for node in ast.walk(tree):
                if isinstance(node, ast.FunctionDef) and node.name == "main":
                    self._convert_main_function(node)
                    break

            # Build the final 4GL code
            result = []

            # Add global defines if any
            for var_name, var_type in self.variables.items():
                result.append(f"DEFINE {var_name} {var_type}")

            if result:
                result.append("")  # Empty line after defines

            # Add main block
            result.extend(self.output)

            return "\n".join(result)

        except Exception as e:
            raise ValueError(f"Failed to convert Python to 4GL: {e}")

    def _convert_main_function(self, func_node: ast.FunctionDef):
        """Convert main() function to MAIN block."""
        self.output.append("MAIN")
        self.indent_level += 1

        for stmt in func_node.body:
            if isinstance(stmt, ast.Expr) and isinstance(stmt.value, ast.Constant):
                # Skip docstrings
                continue
            self._convert_statement(stmt)

        self.indent_level -= 1
        self.output.append("END MAIN")

    def _convert_statement(self, stmt: ast.stmt):
        """Convert a Python statement to 4GL."""
        if isinstance(stmt, ast.AnnAssign):
            # Type annotation: var: str = ""
            self._convert_variable_declaration(stmt)
        elif isinstance(stmt, ast.Assign):
            # Assignment: var = value
            self._convert_assignment(stmt)
        elif isinstance(stmt, ast.Expr):
            # Expression statement (like print())
            self._convert_expression(stmt.value)
        elif isinstance(stmt, ast.If):
            self._convert_if_statement(stmt)
        elif isinstance(stmt, ast.While):
            self._convert_while_statement(stmt)
        elif isinstance(stmt, ast.For):
            self._convert_for_statement(stmt)

    def _convert_variable_declaration(self, stmt: ast.AnnAssign):
        """Convert variable declaration with type annotation."""
        if isinstance(stmt.target, ast.Name):
            var_name = stmt.target.id
            var_type = self._python_type_to_4gl(stmt.annotation)
            self.variables[var_name] = var_type

    def _convert_assignment(self, stmt: ast.Assign):
        """Convert assignment statement."""
        if len(stmt.targets) == 1 and isinstance(stmt.targets[0], ast.Name):
            var_name = stmt.targets[0].id
            value = self._convert_value(stmt.value)

            indent = "    " * self.indent_level
            self.output.append(f"{indent}LET {var_name} = {value}")

    def _convert_expression(self, expr: ast.expr):
        """Convert expression statement."""
        if isinstance(expr, ast.Call):
            if isinstance(expr.func, ast.Name) and expr.func.id == "print":
                # Convert print() to DISPLAY
                args = [self._convert_value(arg) for arg in expr.args]
                indent = "    " * self.indent_level
                self.output.append(f"{indent}DISPLAY {', '.join(args)}")

    def _convert_if_statement(self, stmt: ast.If):
        """Convert if statement."""
        condition = self._convert_value(stmt.test)
        indent = "    " * self.indent_level

        self.output.append(f"{indent}IF {condition} THEN")
        self.indent_level += 1

        for s in stmt.body:
            self._convert_statement(s)

        self.indent_level -= 1

        if stmt.orelse:
            self.output.append(f"{indent}ELSE")
            self.indent_level += 1
            for s in stmt.orelse:
                self._convert_statement(s)
            self.indent_level -= 1

        self.output.append(f"{indent}END IF")

    def _convert_while_statement(self, stmt: ast.While):
        """Convert while statement."""
        condition = self._convert_value(stmt.test)
        indent = "    " * self.indent_level

        self.output.append(f"{indent}WHILE {condition}")
        self.indent_level += 1

        for s in stmt.body:
            self._convert_statement(s)

        self.indent_level -= 1
        self.output.append(f"{indent}END WHILE")

    def _convert_for_statement(self, stmt: ast.For):
        """Convert for statement (limited support)."""
        if isinstance(stmt.iter, ast.Call) and isinstance(stmt.iter.func, ast.Name):
            if stmt.iter.func.id == "range":
                # Convert for i in range(n) to FOR loop
                var_name = stmt.target.id if isinstance(stmt.target, ast.Name) else "i"

                if len(stmt.iter.args) == 1:
                    start = "1"
                    end = self._convert_value(stmt.iter.args[0])
                elif len(stmt.iter.args) == 2:
                    start = self._convert_value(stmt.iter.args[0])
                    end = self._convert_value(stmt.iter.args[1])
                else:
                    start = "1"
                    end = "10"

                indent = "    " * self.indent_level
                self.output.append(f"{indent}FOR {var_name} = {start} TO {end}")
                self.indent_level += 1

                for s in stmt.body:
                    self._convert_statement(s)

                self.indent_level -= 1
                self.output.append(f"{indent}END FOR")

    def _convert_value(self, value: ast.expr) -> str:
        """Convert Python expression to 4GL value."""
        if isinstance(value, ast.Constant):
            if isinstance(value.value, str):
                return f'"{value.value}"'
            else:
                return str(value.value)
        elif isinstance(value, ast.Name):
            return value.id
        elif isinstance(value, ast.BinOp):
            left = self._convert_value(value.left)
            right = self._convert_value(value.right)
            op = self._convert_operator(value.op)
            return f"{left} {op} {right}"
        elif isinstance(value, ast.Compare):
            left = self._convert_value(value.left)
            comparators = [self._convert_value(c) for c in value.comparators]
            ops = [self._convert_compare_op(op) for op in value.ops]
            result = left
            for op, comp in zip(ops, comparators):
                result = f"{result} {op} {comp}"
            return result
        else:
            return "???"

    def _convert_operator(self, op: ast.operator) -> str:
        """Convert Python operator to 4GL operator."""
        if isinstance(op, ast.Add):
            return "+"
        elif isinstance(op, ast.Sub):
            return "-"
        elif isinstance(op, ast.Mult):
            return "*"
        elif isinstance(op, ast.Div):
            return "/"
        else:
            return "+"

    def _convert_compare_op(self, op: ast.cmpop) -> str:
        """Convert Python comparison operator to 4GL."""
        if isinstance(op, ast.Eq):
            return "="
        elif isinstance(op, ast.NotEq):
            return "!="
        elif isinstance(op, ast.Lt):
            return "<"
        elif isinstance(op, ast.LtE):
            return "<="
        elif isinstance(op, ast.Gt):
            return ">"
        elif isinstance(op, ast.GtE):
            return ">="
        else:
            return "="

    def _python_type_to_4gl(self, type_node: ast.expr) -> str:
        """Convert Python type annotation to 4GL type."""
        if isinstance(type_node, ast.Name):
            type_name = type_node.id
            if type_name == "str":
                return "CHAR(50)"
            elif type_name == "int":
                return "INTEGER"
            elif type_name == "float":
                return "DECIMAL(10,2)"
            elif type_name == "bool":
                return "SMALLINT"
        return "CHAR(50)"  # Default


def convert_python_to_4gl(python_code: str) -> str:
    """Convert Python code to 4GL.

    Args:
        python_code: Python source code string

    Returns:
        4GL source code string
    """
    converter = PythonTo4GLConverter()
    return converter.convert(python_code)
