"""
Parser for .4er error files generated by 4make.

Parses compilation errors and warnings from Informix 4GL compiler output.
"""

import re
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional


@dataclass
class CompilationMessage:
    """Represents a compilation error or warning."""

    file: str
    line: Optional[int] = None
    column: Optional[int] = None
    severity: str = "error"  # 'error', 'warning', 'info'
    code: Optional[str] = None  # Error code (e.g., "E1234")
    message: str = ""
    suggestion: Optional[str] = None

    def __str__(self) -> str:
        """Format message for display."""
        location = f"{self.file}"
        if self.line:
            location += f":{self.line}"
            if self.column:
                location += f":{self.column}"

        severity_marker = "❌" if self.severity == "error" else "⚠️"
        result = f"{severity_marker} {location}: {self.message}"

        if self.code:
            result = f"{severity_marker} {location} [{self.code}]: {self.message}"

        if self.suggestion:
            result += f"\n   💡 Suggestion: {self.suggestion}"

        return result


class ErrorFileParser:
    """Parser for .4er error files."""

    # Common error patterns
    PATTERNS = [
        # Pattern: filename:line:column: severity: message
        re.compile(
            r"^(?P<file>[^:]+):(?P<line>\d+):(?P<column>\d+):\s*(?P<severity>error|warning|note|info):\s*(?P<message>.+)$",
            re.IGNORECASE,
        ),
        # Pattern: filename:line: severity: message
        re.compile(
            r"^(?P<file>[^:]+):(?P<line>\d+):\s*(?P<severity>error|warning|note|info):\s*(?P<message>.+)$",
            re.IGNORECASE,
        ),
        # Pattern: filename, line X: message
        re.compile(
            r"^(?P<file>[^,]+),\s*line\s+(?P<line>\d+):\s*(?P<message>.+)$",
            re.IGNORECASE,
        ),
        # Pattern: Error in file.4gl at line X: message
        re.compile(
            r"^(?P<severity>Error|Warning)\s+in\s+(?P<file>[^\s]+)\s+at\s+line\s+(?P<line>\d+):\s*(?P<message>.+)$",
            re.IGNORECASE,
        ),
        # Pattern: file.4gl(line): message
        re.compile(r"^(?P<file>[^\(]+)\((?P<line>\d+)\):\s*(?P<message>.+)$", re.IGNORECASE),
        # Pattern: line X: message (assumes current file)
        re.compile(r"^line\s+(?P<line>\d+):\s*(?P<message>.+)$", re.IGNORECASE),
    ]

    # Error code patterns (e.g., [E1234], (E1234))
    ERROR_CODE_PATTERN = re.compile(r"[\[\(](?P<code>[A-Z]\d+)[\]\)]")

    # Common error suggestions
    SUGGESTIONS = {
        "undeclared": "Check if the variable is declared in the DEFINE section",
        "undefined": "Make sure the function/variable is defined before use",
        "type mismatch": "Check if the types are compatible in this operation",
        "syntax error": "Review the 4GL syntax for this statement",
        "duplicate": "A variable or function with this name already exists",
        "missing end": "Add the corresponding END statement",
        "missing return": "Add a RETURN statement to the function",
        "not found": "Check if the file or resource exists in the project",
    }

    def __init__(self, default_file: str = "unknown"):
        """
        Initialize the error parser.

        Args:
            default_file: Default filename when not specified in error
        """
        self.default_file = default_file
        self.current_file = default_file

    def parse_file(self, file_path: Path) -> List[CompilationMessage]:
        """
        Parse a .4er error file.

        Args:
            file_path: Path to the .4er file

        Returns:
            List of CompilationMessage objects
        """
        if not file_path.exists():
            return []

        with open(file_path, encoding="utf-8", errors="ignore") as f:
            content = f.read()

        return self.parse_content(content)

    def parse_content(self, content: str) -> List[CompilationMessage]:
        """
        Parse error content.

        Args:
            content: Error file content

        Returns:
            List of CompilationMessage objects
        """
        messages = []
        lines = content.split("\n")

        for line in lines:
            line = line.strip()
            if not line:
                continue

            message = self._parse_line(line)
            if message:
                messages.append(message)

        return messages

    def _parse_line(self, line: str) -> Optional[CompilationMessage]:
        """
        Parse a single error line.

        Args:
            line: Error line to parse

        Returns:
            CompilationMessage or None if not recognized
        """
        # Try each pattern
        for pattern in self.PATTERNS:
            match = pattern.match(line)
            if match:
                return self._create_message_from_match(match, line)

        # If no pattern matched, treat as generic error
        if any(keyword in line.lower() for keyword in ["error", "warning", "fatal", "failed"]):
            return CompilationMessage(file=self.current_file, severity="error", message=line)

        return None

    def _create_message_from_match(self, match: re.Match, original_line: str) -> CompilationMessage:
        """
        Create CompilationMessage from regex match.

        Args:
            match: Regex match object
            original_line: Original line for fallback

        Returns:
            CompilationMessage object
        """
        groups = match.groupdict()

        # Extract components
        file = groups.get("file", self.current_file)
        line = int(groups["line"]) if "line" in groups and groups["line"] else None
        column = int(groups["column"]) if "column" in groups and groups["column"] else None
        severity = groups.get("severity", "error").lower()
        message = groups.get("message", original_line).strip()

        # Update current file if specified
        if file:
            self.current_file = file

        # Extract error code if present
        error_code = None
        code_match = self.ERROR_CODE_PATTERN.search(message)
        if code_match:
            error_code = code_match.group("code")

        # Normalize severity
        if severity in ["note", "info"]:
            severity = "info"
        elif severity not in ["error", "warning"]:
            severity = "error"

        # Generate suggestion
        suggestion = self._generate_suggestion(message)

        return CompilationMessage(
            file=file,
            line=line,
            column=column,
            severity=severity,
            code=error_code,
            message=message,
            suggestion=suggestion,
        )

    def _generate_suggestion(self, message: str) -> Optional[str]:
        """
        Generate a helpful suggestion based on the error message.

        Args:
            message: Error message

        Returns:
            Suggestion string or None
        """
        message_lower = message.lower()

        for keyword, suggestion in self.SUGGESTIONS.items():
            if keyword in message_lower:
                return suggestion

        return None


def parse_error_file(file_path: Path, default_file: str = "unknown") -> List[CompilationMessage]:
    """
    Convenience function to parse a .4er error file.

    Args:
        file_path: Path to the .4er file
        default_file: Default filename for errors without file info

    Returns:
        List of CompilationMessage objects
    """
    parser = ErrorFileParser(default_file=default_file)
    return parser.parse_file(file_path)
